Sos 132 fix company menu
StartupOS/startupos pull request #19
Opened 2023-01-04 19:58 UTC by SeanTConrad

This is the big PR to move the company ID into the URL, and eliminate "selected". 

Although "selected" isn't completely gone. It's still used for the company edit form, which I want to redo. I'll open a ticket.

Also includes a fix on table headers on SpendingInsights.

2023-01-04 20:06 UTC, aylusltd commented on client/src/components/CompaniesCard.tsx
> +    console.log('isSelected:',isSelected);
first step to getting out of a hole?

2023-01-04 20:09 UTC, aylusltd requested changes

2023-01-04 20:09 UTC, aylusltd commented on client/src/components/CompaniesPage.tsx
> +    // return (
should remove this

2023-01-04 20:09 UTC, aylusltd commented on client/src/services/companies.tsx
> +
if you remove initialize here, need to remove it from line 83 as well

2023-01-04 20:14 UTC, SeanTConrad commented on client/src/components/CompaniesCard.tsx
> +    console.log('isSelected:',isSelected);
Hmm. The diff is inaccurate. I didn't add that line. The concept of "selected" is still used to launch the edit form.  I opened another ticket to fix that: https://nichols.atlassian.net/browse/SOS-137

I have a prettier MUI form overlay in my old sean-dev branch to copy over.

2023-01-04 20:16 UTC, SeanTConrad commented on client/src/services/companies.tsx
> +
done

2023-01-04 20:16 UTC, SeanTConrad commented on client/src/components/CompaniesPage.tsx
> +    // return (
done

2023-01-04 21:30 UTC, SeanTConrad commented on client/src/services/companies.tsx
> +
Not sure why this doesn't say outdated, I committed the change.

2023-01-05 16:20 UTC, aylusltd commented on client/src/services/companies.tsx
> +
This line is unchanged by the commit. I added the comment in the wrong place.

2023-01-05 16:23 UTC, merged