Sos 136 unify the buttons
StartupOS/startupos pull request #24
Opened 2023-01-06 21:03 UTC by SeanTConrad

Cleaned up some buttons and cards. Fixed bug on Employees page.

2023-01-06 21:09 UTC, aylusltd requested changes

2023-01-06 21:09 UTC, aylusltd commented on client/src/components/AccountCard.tsx
> +    useEffect(() => {
Doesn't this cause a loop? getTransactionsByAccount should update transactionsByAccount.

2023-01-06 21:09 UTC, aylusltd commented on client/src/components/EmployeesPage.tsx
> +    }, [employeesByCompany, getEmployeesByCompany]);
this should also cause a loop

2023-01-06 21:09 UTC, aylusltd commented on client/src/services/api.tsx
> +    id: 1,
Is this on purpose? I'd rather you not simulate me as the user ID... It's hard enough to debug already.

2023-01-07 15:51 UTC, SeanTConrad commented on client/src/services/api.tsx
> +    id: 1,
Sorry. I can set this back. I was trying to QA the Employees page.

2023-01-07 17:05 UTC, SeanTConrad commented on client/src/components/AccountCard.tsx
> +    useEffect(() => {
I only updated the tabs on this code. This is the useEffect running in the current Beta branch, unless I'm misreading the full diff.  However, if should cause a loop. It doesn't though. I removed it and it still all works, so keeping it removed.

I'll isolate tab updates and some console.log removal to its own branch so it's easier to approve.

2023-01-07 17:17 UTC, SeanTConrad commented on client/src/components/EmployeesPage.tsx
> +    }, [employeesByCompany, getEmployeesByCompany]);
Removed and tested. Still works.  This was also the existing way it was.

2023-01-07 17:31 UTC, SeanTConrad commented on client/src/components/AccountCard.tsx
> +    useEffect(() => {
Fix committed

2023-01-07 17:31 UTC, SeanTConrad commented on client/src/components/EmployeesPage.tsx
> +    }, [employeesByCompany, getEmployeesByCompany]);
Fix commited

2023-01-09 14:52 UTC, aylusltd approved these changes

2023-01-09 14:52 UTC, merged