Sos 157 get atd technical metrics into sos report
StartupOS/startupos pull request #27
Opened 2023-01-09 21:38 UTC by SeanTConrad

Pulling "Condensed Report" from ATD in a quick fashion.

Very quick redo of report styles to make it match.

2023-01-09 22:34 UTC, aylusltd commented on client/src/components/types.ts
> +
We should start breaking types out

2023-01-09 22:34 UTC, aylusltd commented on client/src/components/types.ts
> +
Not in this PR, just in general

2023-01-09 22:41 UTC, aylusltd requested changes
Overall looks good, just wanted to trim some commented code. Also might be a useEffect in there with a loop, but I lost it while scrolling.

2023-01-09 22:41 UTC, aylusltd commented on client/src/components/modules/codescan/CodeMetrics.tsx
> +    Object.keys(props.data.project_scan_summary.loc_weighted_mean).map((key)  => (
Please remove

2023-01-09 22:41 UTC, aylusltd commented on client/src/components/modules/codescan/CodeBreakdown.tsx
> +    //const { value, cx, cy, innerRadius, outerRadius, midAngle } = props;
Please remove

2023-01-09 22:41 UTC, aylusltd commented on client/src/components/PLComponent.tsx
>  import colors from 'plaid-threads/scss/colors';
Is this still used anywhere?

2023-01-09 22:41 UTC, aylusltd commented on client/src/components/NetWorth.tsx
> +                <Grid container spacing={2}>
Please remove commented code

2023-01-09 22:41 UTC, aylusltd commented on client/src/components/CompanyReportPage.tsx
> +                <Typography variant="h5" sx={{ mt: 1, mb: 1, fontWeight: 500 }}>Created for <b>{reportData.client}</b></Typography>
please remove commented code

2023-01-09 22:41 UTC, aylusltd commented on client/src/components/BurnChartWidget.tsx
> +        // } else {
Does this work? There should be no delta for at least one month...

2023-01-10 14:22 UTC, SeanTConrad commented on client/src/components/types.ts
> +
Did you mean consolidate types to a shared file? Or actually split them up? Either way, I created a ticket in Sprint 2 to document what we want to do: https://nichols.atlassian.net/browse/SOS-161

2023-01-10 14:36 UTC, SeanTConrad commented
> Overall looks good, just wanted to trim some commented code. Also might be a useEffect in there with a loop, but I lost it while scrolling.

Thanks. I spent some time reading up on useEffect here: https://www.w3schools.com/react/react_useeffect.asp and a few other sources

I was concerned with loops two, so I spent some time with CompanyReportPage.tsx cleaning up the useEffects. I was able to get the page to do much less repetition of logs in the console, meaning some useEffect were running more than necessary. However, if I removed a few dependencies, the page would no longer render and it would just show the loading animation.

I think the useEffect that you are referencing that might cause a loop was in AccountCard.tsx:
` 
useEffect(() => {
        setTransactions(transactionsByAccount[id] || []);
    }, [transactionsByAccount, id]);
 `

I actually took out `transactionsByAccount` with this PR, but now that I look at it, I think it should stay in. `setTransactions` sets `transactions` not `transactionsByAccount`. If the array `transactionsByAccount` were to change for some reason, this useEffect _should_ fire again, updating the page.  However, that never happens, so it doesn't really matter right now.  Still I can fix it if you want.

I also have a ticket open (https://nichols.atlassian.net/browse/SOS-160) to clean up the useEffects in other pages and reduce the redundant rendering. React doesn't allow sharing a useEffect from a child component, util library, or include, so there's a lot of redundant useEffect in multiple files that all need to be updated.

2023-01-10 14:40 UTC, SeanTConrad commented on client/src/components/modules/codescan/CodeMetrics.tsx
> +    Object.keys(props.data.project_scan_summary.loc_weighted_mean).map((key)  => (
Removed. I'm also removing any unused variables to reduce the flaggings at start time and in the console.

And deleting some console.logs.

2023-01-10 14:43 UTC, SeanTConrad commented on client/src/components/modules/codescan/CodeBreakdown.tsx
> +    //const { value, cx, cy, innerRadius, outerRadius, midAngle } = props;
Removed. I'm also standardizing my MUI component imports to this, in alphabetical order:

`
// MUI Components
import { Box, Grid, Paper } from '@mui/material';
`

2023-01-10 14:45 UTC, SeanTConrad commented on client/src/components/PLComponent.tsx
>  import colors from 'plaid-threads/scss/colors';
Removed. And some other unused imports.

2023-01-10 14:48 UTC, SeanTConrad commented on client/src/components/NetWorth.tsx
> +                <Grid container spacing={2}>
Removed. And a note to myself. The dashboard "grid" wrappers should be moved out to SOS components.

2023-01-10 15:04 UTC, SeanTConrad commented on client/src/components/CompanyReportPage.tsx
> +                <Typography variant="h5" sx={{ mt: 1, mb: 1, fontWeight: 500 }}>Created for <b>{reportData.client}</b></Typography>
Done.

2023-01-10 15:24 UTC, SeanTConrad commented on client/src/components/BurnChartWidget.tsx
> +        // } else {
Honestly, I'm not sure. 

This was copied from BurnChart.tsx, because it's embedded in the company page as well. There was a rabbit hole of UI changes to make it work in both and recharts UI is really brittle.

There's a lot going on with this chart and I don't have very good data to QA with. SOS's account isn't updating. And Pickle hasn't updated since May 2022. 

IMO, this chart is really hard to read. I would like to updated it to look something like this:
![burnrateforecast](https://user-images.githubusercontent.com/78375852/211591173-1d74c5be-c4fb-45c4-a0ac-ecf03c9c5339.png)

I will open a ticket for that.

2023-01-12 02:30 UTC, SeanTConrad commented
Last commit looks good.

2023-01-12 16:13 UTC, aylusltd approved these changes

2023-01-12 16:13 UTC, merged