Sos 125 add missing pages
StartupOS/startupos pull request #30
Opened 2023-01-12 21:21 UTC by SeanTConrad

Changes include:
- Alphabetizing list of pages everywhere including index.ts and App.tsx
- Moving page components to their own directory
- Creating new pages:
- About
- Terms of Use
- Privacy Policy
- My Account
- Fixing the menu and footer to point to the correct pages
- Unit test for some of the page
- Deleting some binary called ".SOSButton.tsx.swp" committed in the crypto PR

2023-01-14 04:34 UTC, aylusltd commented on client/src/App.tsx
> +import { AssetsProvider } from './services/assets';
why not just
```
    import {
        ...
    } from './services'
```

2023-01-14 04:46 UTC, aylusltd requested changes
Minor stuff, mostly not sure we should be mirroring marketing/legal content into the app, prefer to keep that stuff on the marketing site so it doesn't take a PR to edit.

That being said, that's mostly an instinctual thing at this point, so if you've got an argument in favor, it's not that big a deal to me.

2023-01-14 04:46 UTC, aylusltd commented on client/src/App.tsx
> +                                            <Route path="/Company/:companyIdParam/Dashboard" element={<CompanyReportPage/>} />
can you pass props here? Prob best way to get company id

2023-01-14 04:46 UTC, aylusltd commented on client/src/components/Footer.tsx
> +                <Link to="/Terms"  component={NavLink}
Do we want these in app? Shouldn't they be in the marketing site for ease of edit/styling?

2023-01-14 04:46 UTC, aylusltd commented on client/src/components/Footer.tsx
> +                <Link to="/Terms"  component={NavLink}
https://www.startupos.dev/about-us/terms-and-conditions

2023-01-14 04:46 UTC, aylusltd commented on client/src/components/Footer.tsx
> +                <Link to={"/Privacy"} component={NavLink}
https://www.startupos.dev/about-us/privacy

2023-01-14 04:46 UTC, aylusltd commented on client/src/components/pages/AboutPage.tsx
> +
Why duplicate fluff content here? It'll only hurt us on SEO if this ever actually gets indexed.

2023-01-14 04:46 UTC, aylusltd commented on client/src/components/pages/MyAccountPage.tsx
> +        if (userState !== undefined && userState !== null && userState.currentUser !== undefined && userState.currentUser.id !== undefined ) {
maybe nest these ifs since they share common conditions? Or consider abstracting to a function? That you export... and unit test. :)

Not a deal breaker or anything, but rule of three and all.

2023-01-14 04:46 UTC, aylusltd commented on client/src/components/pages/PrivacyPage.tsx
> +import React from 'react';
Same comment as about... I'd rather the link just open the marketing site in a new tab. Less code == more good.

2023-01-14 04:46 UTC, aylusltd commented on client/src/components/pages/TermsPage.tsx
> +import React from 'react';
Same as above.

2023-01-16 16:04 UTC, SeanTConrad commented on client/src/App.tsx
> +import { AssetsProvider } from './services/assets';
These had never been added to the services/index.js, so it wouldn't work. Added and changed to the common format.

2023-01-16 17:20 UTC, SeanTConrad commented on client/src/components/pages/MyAccountPage.tsx
> +        if (userState !== undefined && userState !== null && userState.currentUser !== undefined && userState.currentUser.id !== undefined ) {
Cleaned up a bit. This was probably left over from me fighting with type script.

2023-01-17 15:35 UTC, aylusltd commented on client/src/App.tsx
> +                                            <Route path="/Company/:companyIdParam/Dashboard" element={<CompanyReportPage/>} />
You can do `<Route path="/Company/:companyIdParam/Accounts" element={<AccountsPage companyId={companyIdParam} />} />` I think

2023-01-17 15:56 UTC, merged