SOS-130 Messages should clear
StartupOS/startupos pull request #35
Opened 2023-01-20 17:17 UTC by SeanTConrad

Changes include:

- Unread messages are bold
- Clicking calls API to mark messages as read
- Pointer cursor over message to mark as clickable
- Messages sorted newest to oldest
- Badge now shows just number of unread

2023-01-22 17:02 UTC, SeanTConrad commented
There's still some bugs with Messages. Some old messages don't have great data (null created at). 

The linked sharing page is a bit confusing. 

There's no place to see all historic messages. And messages are never deleted.

But it's good enough for demo purposes and better than it was before this ticket.

2023-01-23 15:53 UTC, aylusltd commented on client/src/components/AlertMessage.tsx
>      const to='You',
This doesn't need to be changed, but there should be a message.recipient and message.recipient_org if you want to use them.

2023-01-23 15:55 UTC, aylusltd commented on client/src/components/NetWorth.tsx
> +                            <p className="dataItem">Cash</p>{' '}
Should this be hardcoded? We can read it from the account types.

2023-01-23 15:57 UTC, aylusltd requested changes

2023-01-23 15:57 UTC, aylusltd commented on client/src/components/Alerts.tsx
> +    const [ messages, setMessages ] = useState<ExpandedMessageType[]>([]);
Why two message states?

2023-01-23 16:23 UTC, SeanTConrad commented on client/src/components/NetWorth.tsx
> +                            <p className="dataItem">Cash</p>{' '}
For NetWorth, I only fixed a bug where they styling for the version without liabilities didn't match the version with. This is all the old, original code. I will add a ticket in the backlog to make this MUI, more typed, etc.

2023-01-23 16:25 UTC, SeanTConrad commented on client/src/components/AlertMessage.tsx
>      const to='You',
Both "You" and "Me" were hardcoded when I started. I didn't know if this list ever showed my sent messages. If it always just show my inbox, "You" is very clean from a UI perspective.

2023-01-23 18:27 UTC, aylusltd commented on client/src/components/Alerts.tsx
> +    const [ messages, setMessages ] = useState<ExpandedMessageType[]>([]);
This is still in the PR, did you push that?

2023-01-23 19:08 UTC, merged