Sos 191 api rendering unit testing
StartupOS/startupos pull request #41
Opened 2023-01-26 21:54 UTC by SeanTConrad

2023-01-26 21:58 UTC, SeanTConrad commented
This test is rendering the Companie page with sample user, employees, and companies data via the Providers. There's a lot to do, but it does greatly increase our test coverage.

2023-01-27 00:04 UTC, aylusltd requested changes

2023-01-27 00:04 UTC, aylusltd commented on client/src/components/pages/CompaniesPage.test.tsx
> +        "date_of_birth": "1986-02-28T00:00:00.000Z"
No PII in the repo.

2023-01-27 15:26 UTC, aylusltd approved these changes
LGTM

2023-01-27 16:08 UTC, merged