Sos 218 update spending pie chart to use new subcategories
StartupOS/startupos pull request #43
Opened 2023-02-03 21:27 UTC by SeanTConrad

2023-02-04 20:34 UTC, aylusltd commented on client/src/components/types.ts
> +  sos_category: string;
should make this an enum

2023-02-04 20:35 UTC, aylusltd commented on client/src/components/WidgetDescription.tsx
> +    Widget explination text for report dashboard.
explanation

2023-02-04 20:36 UTC, aylusltd commented on client/src/components/WidgetDescription.test.tsx
> +    render(<WidgetDescription>This is just some text.</WidgetDescription>);
these should be different tests

2023-02-04 20:40 UTC, aylusltd commented on client/src/components/SpendingBreakdown.tsx
> +    let arr = transactions.map(t=>Date.parse(t.date))
Do we still need this?

2023-02-04 20:44 UTC, aylusltd requested changes

2023-02-04 20:44 UTC, aylusltd commented on client/src/components/WidgetDescription.test.tsx
> +    render(<WidgetDescription>This is just some text.</WidgetDescription>);
these should be different tests

2023-02-07 15:04 UTC, aylusltd requested changes

2023-02-07 15:04 UTC, aylusltd commented on client/src/components/WidgetDescription.test.tsx
> +    render(<WidgetDescription>This is just some text.</WidgetDescription>);
These should be separate tests

2023-02-07 18:29 UTC, SeanTConrad commented on client/src/components/types.ts
> +  sos_category: string;
Just tried, but even with bogus values, it just accepts what the API sends back:
![image](https://user-images.githubusercontent.com/78375852/217333803-15883f1f-4c3f-46a8-a974-f48b4bc7bb1c.png)

2023-02-08 15:02 UTC, aylusltd requested changes
Minor stuff

2023-02-08 15:02 UTC, aylusltd commented on client/src/components/SpendingBreakdown.tsx
> +            const cumCategories = categoryPercents.reduce((p,c,index)=>{ return index<=j?p+c:p });
I have to imagine there's a better name for this...

2023-02-08 15:02 UTC, aylusltd commented on client/src/components/SpendingBreakdown.tsx
> +  const options: Highcharts.Options = {
should this go in a theme?

2023-02-08 19:46 UTC, SeanTConrad commented on client/src/components/WidgetDescription.tsx
> +    children: string | JSX.Element | JSX.Element[] | (string | JSX.Element)[];
The union is an array of strings or JSX Elements.

2023-02-08 19:48 UTC, SeanTConrad commented on client/src/components/SpendingBreakdown.tsx
> +    const categoriesObject = useMemo((): CategorySummary => {
I check this against a database query, so I don't have a value to match against in the unit test. It's really difficult to get values out of a highchart as well.

2023-02-08 19:49 UTC, SeanTConrad commented on client/src/components/SpendingBreakdown.tsx
> +    const categoryColorLevel = 800;
Chart colors aren't in the themes yet. This was just a quick way to get color gradients for the subcategories.

2023-02-08 19:50 UTC, SeanTConrad commented on client/src/components/SpendingBreakdown.tsx
> +        const cumeExpenses = expensePercents.reduce((p,c,index)=>{ return index<=i?p+c:p });
I think I fixed it. I am lost without a red squiggle.

2023-02-08 19:51 UTC, SeanTConrad commented on client/src/components/SpendingBreakdown.tsx
> +            const cumCategories = categoryPercents.reduce((p,c,index)=>{ return index<=j?p+c:p });
Whoops! fixed

2023-02-08 19:54 UTC, SeanTConrad commented on client/src/components/SpendingBreakdown.tsx
> +  const options: Highcharts.Options = {
same as above. Someday I'll add a theme "base red", but it's a low priority. Current way helps us keep it close to ADA compliance too.

2023-02-08 20:13 UTC, aylusltd commented on client/src/components/WidgetDescription.tsx
> +    children: string | JSX.Element | JSX.Element[] | (string | JSX.Element)[];
right, which should accept an array of JSX Elements as well

2023-02-08 20:40 UTC, aylusltd commented on client/src/components/SpendingBreakdown.tsx
> +        const cumeExpenses = expensePercents.reduce((p,c,index)=>{ return index<=i?p+c:p });
hasn't changed here. would also prefer a different var name if not too much trouble...

2023-02-08 20:42 UTC, SeanTConrad commented on client/src/components/WidgetDescription.tsx
> +    children: string | JSX.Element | JSX.Element[] | (string | JSX.Element)[];
Ah, fixed.

2023-02-08 20:44 UTC, merged