SOS-202 removed unused items, console.log
StartupOS/startupos pull request #44
Opened 2023-02-06 15:41 UTC by SeanTConrad

This seems like a beast, and it is. But the changes are just removing unused variables that triggered compiler warnings AND removing a bunch of console.logs. Some were changed to console.errors when they we catching errors in a try/catch.

2023-02-08 20:39 UTC, aylusltd requested changes
1 change requested

2023-02-08 20:39 UTC, aylusltd commented on client/src/components/pages/SignInPage.tsx
> +    // function logIn (provider: string) {//event: React.SyntheticEvent | Event, reason?: string) => {
can we just delete this?

2023-02-12 16:54 UTC, SeanTConrad commented on client/src/components/pages/SignInPage.tsx
> +    // function logIn (provider: string) {//event: React.SyntheticEvent | Event, reason?: string) => {
fixed

2023-02-13 21:29 UTC, aylusltd approved these changes

2023-02-13 21:33 UTC, merged