SOS-102   add MUI theme support
StartupOS/startupos pull request #5
Opened 2022-12-23 19:04 UTC by SeanTConrad

Added MUI themes. Set theme in .env with REACT_APP_THEME.

Added footer too so you can see the theme in action. Colors and company name are from theme.

2022-12-23 21:34 UTC, aylusltd requested changes

2022-12-23 21:34 UTC, aylusltd commented on client/src/components/index.ts
> +export { default as Footer} from './Footer'
please add a newline at the end of the files

2022-12-23 21:34 UTC, aylusltd commented on client/src/components/Footer.tsx
> +  }
please add a newline here

2022-12-23 21:45 UTC, SeanTConrad commented on client/src/components/index.ts
> +export { default as Footer} from './Footer'
Added to all files in the PR.

2022-12-23 21:45 UTC, SeanTConrad commented on client/src/components/Footer.tsx
> +  }
done

2022-12-24 01:32 UTC, aylusltd approved these changes

2022-12-24 01:32 UTC, merged