Sos 228 enumerate the task necessary to make the target wizard mvp
StartupOS/startupos pull request #57
Opened 2023-03-03 21:46 UTC by SeanTConrad

Working onboarding wizard for targets

2023-03-06 17:20 UTC, aylusltd requested changes

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/AddCompanyForm.tsx
> -        setFormCompany(null);
Why did you remove this?

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/BurnChart.tsx
>    window["Jason"]=data
We should remove this

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/CompaniesCard.tsx
> +                        width={165}
this will result in a fractional pixel width... Should we update the default and the formulas?

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/CompanyBox.tsx
> +                    src={logo} onError={(e:React.SyntheticEvent<HTMLImageElement>) => e.currentTarget.src="/generic_company.png"}
isn't this the same as ` logo || '/generic_company.png'`

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/CompanyBox.tsx
> +                display:'flex',
Can we delete these?

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/TopAppBar.tsx
> -import { useTheme } from '@mui/material/styles';
?? Shouldn't we keep this?

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/TopAppBar.tsx
> +            return companiesByUser.companies.filter((c)=>c.is_funder).length > 0
why only funder companies here?

2023-03-06 17:20 UTC, aylusltd commented on client/src/components/pages/AccountsPage.tsx
> +    if (currentCompany === null || companyId === null){
can companyId ever not be null if currentCompany is?

2023-03-06 18:59 UTC, SeanTConrad commented on client/src/components/AddCompanyForm.tsx
> -        setFormCompany(null);
It was resetting a form that's hidden. Now if the user launched Edit on the same company twice, it's still there. But if they click Edit on a new company, the content gets replaced anyways.

I needed the form company for the Wizard page to show new companies in the interface:
![image](https://user-images.githubusercontent.com/78375852/223204978-21a5d906-c08d-4f6a-9034-651ac705c9dc.png)

After the company is created, ListCompanies updates the list, but I needed to know which company is the new one to display it. This was a handy place to get it.

2023-03-06 19:05 UTC, SeanTConrad commented on client/src/components/CompanyBox.tsx
> +                    src={logo} onError={(e:React.SyntheticEvent<HTMLImageElement>) => e.currentTarget.src="/generic_company.png"}
Combined the two methods. The React Synthetic event catches when logo is defined, but it's a bad URL. Currently happening in Negentropy I think.

2023-03-06 19:08 UTC, SeanTConrad commented on client/src/components/pages/AccountsPage.tsx
> +    if (currentCompany === null || companyId === null){
No, but Typescript doesn't know that. This prevents a bunch of code below checking companyId for null.

2023-03-06 19:11 UTC, SeanTConrad commented on client/src/components/pages/EmployeesPage.tsx
> +    },[generateLinkToken, currentCompany, userState, companyId])
I had a bunch of issues with EmployeesPage and AccountPage not showing buttons of first view, but after refresh. So I had to tweak useEffects to get it to load. This is an artifact of that. Reverted.

2023-03-06 19:16 UTC, SeanTConrad commented on client/src/components/pages/EmployeesPage.tsx
> +                    {canLink && companyId && (
It's for Typescript. That's why I had tried adding it to the LoaderAnimation return. But TS was still barking at companyId possible being undefined in a place where it could never be undefined.

2023-03-06 19:16 UTC, SeanTConrad commented on client/src/components/pages/AccountsPage.tsx
> +    }, [currentCompany, generateLinkToken]);
fixed

2023-03-06 19:18 UTC, SeanTConrad commented on client/src/components/pages/TargetSignUpPage.tsx
> +                return (
It's within:
`{steps.map((step:StepType, index) => {`

so it's returning a list of steps.

2023-03-07 03:42 UTC, aylusltd commented on client/src/components/pages/TargetSignUpPage.tsx
> +                return (
I was looking for that, but the expand up never seemed to show a start... My bad.

2023-03-07 03:42 UTC, aylusltd approved these changes

2023-03-07 03:43 UTC, merged