SOS-119 Added links to company cards
StartupOS/startupos pull request #6
Opened 2022-12-26 15:51 UTC by SeanTConrad

See screenshots of changes here: https://nichols.atlassian.net/browse/SOS-119
The links in the top nav bar for Accounts, Employees, and Reporting (AKA Sharing) are relevant to an individual company and confusing at the top.

In order to support eventually removing them, add links to the same content in the Company Card (for companies the user has access to updating).

Added the links. The Selected company is still shown in a blue border with a Grid item.

Links are just on companies for which the user is an owner. I also made it all cleaner, and fonts now come from the Theme.

To do in the future:
- Clean up and center the graphs (Remaining cash, etc.)
- Once users no longer need to select a company, get rid of the “double border”.
- The links pass the company ID at the end of the URL, Eventually, those pages should read the ID from the path.
- Also, we need to be consistent in terminology between “Dashboard” and “Report”. I prefer “Report” because that’s what we use with prospective customers.

2022-12-27 16:09 UTC, SeanTConrad commented
Researching a possible bug introduced with this change "Warning: React has detected a change in the order of Hooks called by CompaniesPage."

2022-12-28 14:55 UTC, aylusltd requested changes

2022-12-28 14:55 UTC, aylusltd commented on client/src/components/CompaniesCard.tsx
>  }
please add trailing new line

2022-12-28 15:56 UTC, SeanTConrad commented on client/src/components/CompaniesCard.tsx
>  }
Fixed. Also added a setting in VSCode to do this automatically.

2022-12-28 17:02 UTC, aylusltd approved these changes

2022-12-28 17:02 UTC, merged