2022 12 29 merge par tah
StartupOS/startupos pull request #9
Opened 2022-12-30 01:50 UTC by SeanTConrad

All my changes merged and QA'ed

2022-12-30 05:03 UTC, aylusltd requested changes

2022-12-30 05:03 UTC, aylusltd commented on client/src/index.scss
> -$threads-font-path: '~plaid-threads/fonts';
did you leave an empty file?

2022-12-31 16:47 UTC, SeanTConrad commented on client/public/sean.jpeg:Zone.Identifier
> +[ZoneTransfer]
I'll remove it. It was to QA styling of the avatar on the local machine, since LinkedIn Auth doesn't work in the local machine.

2022-12-31 16:50 UTC, SeanTConrad commented on client/src/App.tsx
> +    UserList,
I'm not sure I understand. This change was just removing "Menu" since it gets added by the Company related pages.

2022-12-31 16:56 UTC, SeanTConrad commented on client/src/App.tsx
> -export default withRouter(App);
This is actually unnecessary with react-router-dom v 6.  https://reactrouter.com/en/main/routers/create-browser-router

The router gets added in "index.js" with:
`import {BrowserRouter as Router} from 'react-router-dom';
import './index.scss';
import App from './App';

ReactDOM.render(
  <Router>
    <App />
  </Router>,
  document.getElementById('root')
);`

I also am standardizing on the functional declaration for component that seems to be recommend and used in MUI examples:
`export default function MyComponent () {}`

2022-12-31 16:59 UTC, SeanTConrad commented on client/src/components/AccountsPage.tsx
> +export default function AccountsPage () {
In react-router-dom v6, this is replaced with:
`import {useParams} from 'react-router-dom';
  const params = useParams();`

https://typescript.tv/react/upgrade-to-react-router-v6/

2022-12-31 17:01 UTC, SeanTConrad commented on client/src/components/AlertMessage.tsx
>          flip();
I opened a new ticket https://nichols.atlassian.net/browse/SOS-130

2022-12-31 17:03 UTC, SeanTConrad commented on client/src/components/Avatar.tsx
> +            <div>
Avatar.tsx was replaced by "AccountMenu.tsx" so that it's all styled from MUI themes. I'll delete Avatar.tsx.

2022-12-31 17:06 UTC, SeanTConrad commented on client/src/components/CompanyReportPage.tsx
> +                running and that your .env file has been configured correctly.
Hmm, that's weird. I didn't change that at all. I only changed a few DIV to MUI Container or Box.  I'm restyling this page next week to separate companies Shared With Me and Companies I Own.

2022-12-31 17:09 UTC, SeanTConrad commented on client/src/components/Footer.tsx
> +import { ChatButton } from ".";
Good catch. I did move it back to the Nav Bar. There should have been a second button in the Footer, but I don't see it for some reason. Removed it from this file anyways.

2022-12-31 17:10 UTC, SeanTConrad commented on client/src/index.scss
> -$threads-font-path: '~plaid-threads/fonts';
I did. Removed. custom.css was also there and empty. Deleted.

2022-12-31 17:13 UTC, SeanTConrad commented
Happy New Year! I just committed the requested changes.

2023-01-02 15:15 UTC, aylusltd requested changes

2023-01-02 15:15 UTC, aylusltd commented on client/src/App.tsx
> +    UserList,
UserList is a vulnerability. While we're in the big merge PR touching all the files might as well delete it.

2023-01-02 15:15 UTC, aylusltd commented on client/src/components/CompanyReportPage.tsx
> +                running and that your .env file has been configured correctly.
Yeah, it's from Plaid boilerplate, I saw it in the commit history. We can kill it later.

2023-01-02 18:52 UTC, aylusltd approved these changes

2023-01-02 18:52 UTC, merged